#!/usr/bin/env bash

~/graphx/sbin/stop-all.sh
sleep 10
~/graphx/sbin/stop-all.sh
# if [ -z "$1" ]
#   then
cd ~/graphx; sbt/sbt assembly;
# fi
~/spark-ec2/copy-dir --delete ~/graphx
sleep 20
~/graphx/sbin/start-all.sh



