#!/usr/bin/env bash

/mnt/graphx/sbin/stop-all.sh
sleep 10
/mnt/graphx/sbin/stop-all.sh
# mv ~/graphx /mnt
# rm -rf ~/graphx
# if [ -z "$1" ]
#   then
cd /mnt/graphx; sbt/sbt assembly;
# cp -r /mnt/graphx ~/
# fi
~/spark-ec2/copy-dir --delete /mnt/graphx
sleep 20
/mnt/graphx/sbin/start-all.sh



